#!/usr/bin/env sh

clean="/home/mic/python/cli_apps/cli_apps/clean_files/"

sed -re "s/\\\\n/ /g" "${clean}final_list.txt" > "${clean}res0.txt"
sed -re "s/\\\//g"  "${clean}res0.txt" > "${clean}res1.txt"
# sed -re "s/]//g" "${clean}res1.txt" > "${clean}res2.txt"
sed -re "s/ ''//g" "${clean}res1.txt" > "${clean}res3.txt"
sed -re "s/ '\)/'\)/g" "${clean}res3.txt" > "${clean}res4.txt"
sed -re "s/,,/,/g" "${clean}res4.txt" > "${clean}res5.txt"
# sed -re 's/",/,/g'"${clean}res5.txt" > "${clean}res6.txt"
# sed -re "s/.,/, /g""${clean}res6.txt" > "${clean}res7.txt"
# sed -re "s/,./, /g" "${clean}res7.txt" > "${clean}res8.txt"
sed -re "s/ ,.,/. /g" "${clean}res5.txt" > "${clean}res9.txt"
sed -re 's/ ,"/"/g' "${clean}res9.txt" > "${clean}res10.txt"
sed -re 's/"//g' "${clean}res10.txt" > "${clean}res11.txt"
sed -re "s/ , /, /g" "${clean}res11.txt" > "${clean}res12.txt"
# sed -re "s/\( ,  '  ,  ' //g" "${clean}res12.txt" > "${clean}res13.txt"
# sed -re "s/\(,  '  ,  ' //g" "${clean}res13.txt" > "${clean}res14.txt"
sed -re "s/' , '/,/g" "${clean}res12.txt" > "${clean}res15.txt"
# sed -re "s/ ',  /, /g" "${clean}res15.txt" > "${clean}res16.txt"
sed -re "s/,  /, /g" "${clean}res15.txt" > "${clean}res17.txt"
# sed -re "s/ , /, /g" "${clean}res17.txt" > "${clean}res18.txt"
sed -re "s/'//g" "${clean}res17.txt" > "${clean}res19.txt"
# sed -re "s/ ., //g" "${clean}res19.txt" > "${clean}res20.txt"
# sed -re "s/, ,//g" "${clean}res20.txt" > "${clean}res21.txt"
# sed -re "s/^\(,   /\(/g" "${clean}res21.txt" > "${clean}res22.txt"
sed -re "s/.,,/, /g" "${clean}res19.txt" > "${clean}res23.txt"
sed -re "s/  / /g" "${clean}res23.txt" > "${clean}res24.txt"
sed -re "s/([[:alpha:]]),([[:alpha:]])/\1, \2/g" "${clean}res24.txt" > "${clean}res25.txt"
# sed -re "s/\[description , /\[/g" "${clean}res25.txt" > "${clean}res26.txt"
# sed -re "s/ , / /g" "${clean}res26.txt" > "${clean}res27.txt"
# sed -re 's/([[:punct:]])(https.*$)/\1 \2/g' "${clean}res27.txt" > "${clean}res28.txt"
# sed -re 's/([[:punct:]])( https.*$)/\1],\2/g' "${clean}res28.txt" > "${clean}res29.txt"
# sed -re "s/\(//g" "${clean}res29.txt" > "${clean}res30.txt"
# sed -re "s/\)//g" "${clean}res30.txt" > "${clean}res31.txt"
sed -re "s/\{description: \[\]\}//g" "${clean}res25.txt" > "${clean}res32.txt"
sed -re "s/(,  ){2,}/,/g" "${clean}res32.txt" > "${clean}res33.txt"
sed -re "s/\[ {1}[[:punct:]]{2,}//g" "${clean}res33.txt" > "${clean}res34.txt"
sed -re "s/\[\{description: \[\W+\]//g" "${clean}res34.txt" > "${clean}res35.txt"
sed -re "s/\[\]//g" "${clean}res35.txt" > "${clean}res36.txt"
sed -re "s/\([A-Za-z]+, \), //g" "${clean}res36.txt" > "${clean}res37.txt"
sed -re "s/>>>>>//g" "${clean}res37.txt" > "${clean}res38.txt"
sed -re "s/<<<<<//g" "${clean}res38.txt" > "${clean}res39.txt"
sed -re "s/ , , /, /g" "${clean}res39.txt" > "${clean}res40.txt"
sed -re "s/ ,, //g" "${clean}res40.txt" > "${clean}res41.txt"
sed -re "s/\[,+ /\[/g" "${clean}res41.txt" > "${clean}res42.txt"
sed -re "s/\[\W+/\[/g" "${clean}res42.txt" > "${clean}res43.txt"
sed -re "s/\}//g" "${clean}res43.txt" > "${clean}res44.txt"
sed -re "s/\]\]\)/\]\)/g" "${clean}res44.txt" > "${clean}res45.txt"
sed -re "s/(I|and|or), /\1/g" "${clean}res45.txt" > "${clean}res46.txt"
sed -re "s/ .,, //g" "${clean}res46.txt" > "${clean}res47.txt"

mv "${clean}res25.txt" "${clean}final_text.txt"
